//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MILANO_64131856.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MILANO_64131856Entities : DbContext
    {
        public MILANO_64131856Entities()
            : base("name=MILANO_64131856Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }
        public virtual DbSet<ChiTietPhieuXuat> ChiTietPhieuXuats { get; set; }
        public virtual DbSet<LoaiSanPham> LoaiSanPhams { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<PhieuNhap> PhieuNhaps { get; set; }
        public virtual DbSet<PhieuXuat> PhieuXuats { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
    
        public virtual int LoaiSanPham_TimKiem(string maLoai, string tenLoai)
        {
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(string));
    
            var tenLoaiParameter = tenLoai != null ?
                new ObjectParameter("TenLoai", tenLoai) :
                new ObjectParameter("TenLoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LoaiSanPham_TimKiem", maLoaiParameter, tenLoaiParameter);
        }
    
        public virtual int SanPham_TimKiem(string maSanPham, string tenSanPham, string maLoai)
        {
            var maSanPhamParameter = maSanPham != null ?
                new ObjectParameter("MaSanPham", maSanPham) :
                new ObjectParameter("MaSanPham", typeof(string));
    
            var tenSanPhamParameter = tenSanPham != null ?
                new ObjectParameter("TenSanPham", tenSanPham) :
                new ObjectParameter("TenSanPham", typeof(string));
    
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SanPham_TimKiem", maSanPhamParameter, tenSanPhamParameter, maLoaiParameter);
        }
    
        public virtual ObjectResult<TinhToanHangTonKho_Result> TinhToanHangTonKho()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TinhToanHangTonKho_Result>("TinhToanHangTonKho");
        }
    }
}
