//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeTrucTuyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public int id { get; set; }
        public int id_khach_hang { get; set; }
        public Nullable<int> id_xe { get; set; }
        public Nullable<int> so_sao { get; set; }
        public string binh_luan { get; set; }
        public Nullable<System.DateTime> ngay_danh_gia { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Xe Xe { get; set; }
    }
}
