//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeTrucTuyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanhThu
    {
        public int id { get; set; }
        public System.DateTime ngay { get; set; }
        public decimal tong_tien { get; set; }
        public int id_don_thue_xe { get; set; }
    
        public virtual DonThueXe DonThueXe { get; set; }

        public virtual KhachHang KhachHang { get; set; }
        public virtual Xe Xe { get; set; }

    }
}
