//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThueXeTrucTuyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonThueXe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonThueXe()
        {
            this.DoanhThus = new HashSet<DoanhThu>();
        }
    
        public int id { get; set; }
        public int id_khach_hang { get; set; }
       
        public Nullable<int> id_xe { get; set; }
        public System.DateTime ngay_bat_dau { get; set; }
        public System.DateTime ngay_ket_thuc { get; set; }
        public decimal tong_tien { get; set; }
        public string trang_thai { get; set; }
        public Nullable<int> id_nhan_vien_xu_ly { get; set; }
       

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoanhThu> DoanhThus { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual Xe Xe { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
